export type Scene = { a: number; b: number; label: string };
export type Cue = { t0: number; t1: number; s: string };
export declare const SCENES: Scene[];
export declare const FILM_END: number;
export declare const CUES: Cue[];
export declare const INK: string;
export declare const PAPER: string;
export declare function drawScene(idx: number, t: number): string;
export declare function paper(): string;
export declare function drawCast(t: number): string;
